# Basic Information 
title: Xin Zhe Khooi
position: Ph.D. Student
affiliation: National University of Singapore
email: khooixz (at) comp.nus.edu.sg

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Xin Zhe Khooi
description: Xin Zhe Khooi | Ph.D. Student
# canonical: https://minimal-light.yyliu.net/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=AocOAkMAAAAJ&hl=en
github_link: https://github.com/khooi8913
linkedin: https://www.linkedin.com/in/xinzhekhooi/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.ico
favicon_dark: ./assets/img/favicon.ico

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: G-VS7NSRT4S4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
